import { useState } from 'react';
import { RefreshCw, Wand2 } from 'lucide-react';

export function VibeCheck() {
    const [inputText, setInputText] = useState('');
    const [isChecking, setIsChecking] = useState(false);
    const [result, setResult] = useState(null);

    const handleCheck = () => {
        if (!inputText.trim()) return;
        setIsChecking(true);
        setResult(null);

        // Simulate API call to Cloudflare Worker
        setTimeout(() => {
            setIsChecking(false);
            setResult({
                wordsToCut: ["delve", "testament", "tapestry", "navigate", "unlock"],
                rewrite: "Here is a much more direct, human-sounding version of your text. Notice how we cut the generic AI filler words and prioritized clarity and action. You don't need to 'navigate the tapestry' when you can just 'start building'."
            });
        }, 1500);
    };

    return (
        <div className="max-w-4xl mx-auto py-8">
            <div className="mb-8">
                <h2 className="text-3xl font-serif text-zinc-100 mb-2">The Vibe Check Protocol</h2>
                <p className="text-zinc-400">Never publish "Slop". Run AI-generated content through this scanner to detect and remove robotic language.</p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-6 flex flex-col h-[500px]">
                    <h3 className="font-semibold text-zinc-200 mb-4 flex items-center gap-2">
                        <span className="w-2 h-2 rounded-full bg-rose-500"></span>
                        Raw AI Output
                    </h3>
                    <textarea
                        className="w-full flex-1 bg-zinc-950 border border-zinc-800 rounded-lg p-4 text-zinc-300 focus:outline-none focus:border-rose-500/50 resize-none transition-colors"
                        placeholder="Paste the text generated by the AI here..."
                        value={inputText}
                        onChange={e => setInputText(e.target.value)}
                    />
                    <button
                        onClick={handleCheck}
                        disabled={isChecking || !inputText.trim()}
                        className="mt-6 flex items-center justify-center gap-2 w-full bg-rose-600 hover:bg-rose-500 disabled:opacity-50 disabled:hover:bg-rose-600 text-white font-medium py-3 rounded-lg transition-all"
                    >
                        {isChecking ? <RefreshCw className="animate-spin" size={18} /> : <Wand2 size={18} />}
                        <span>{isChecking ? 'Scanning for Slop...' : 'Run Vibe Check'}</span>
                    </button>
                </div>

                <div className="bg-zinc-950 border border-zinc-800 rounded-xl p-6 relative flex flex-col h-[500px]">
                    <h3 className="font-semibold text-emerald-400 mb-4 flex items-center gap-2">
                        <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
                        Humanized Result
                    </h3>

                    {!result && !isChecking && (
                        <div className="flex-1 flex flex-col items-center justify-center text-zinc-600">
                            <Wand2 size={48} className="mb-4 opacity-20" />
                            <p>Waiting for text to scan...</p>
                        </div>
                    )}

                    {isChecking && (
                        <div className="flex-1 flex flex-col items-center justify-center text-rose-400 space-y-4">
                            <div className="w-16 h-16 border-4 border-rose-500/20 border-t-rose-500 rounded-full animate-spin"></div>
                            <p className="font-mono text-sm tracking-wider uppercase animate-pulse">Running heuristic analysis</p>
                        </div>
                    )}

                    {result && (
                        <div className="flex-1 overflow-y-auto space-y-6">
                            <div className="bg-rose-500/10 border border-rose-500/20 rounded-lg p-4">
                                <h4 className="text-xs font-bold uppercase tracking-wider text-rose-400 mb-2">Words to Cut</h4>
                                <div className="flex flex-wrap gap-2">
                                    {result.wordsToCut.map(word => (
                                        <span key={word} className="bg-zinc-950 border border-rose-500/30 text-rose-300 px-2 py-1 rounded text-sm line-through decoration-rose-500/50 underline-offset-4">
                                            {word}
                                        </span>
                                    ))}
                                </div>
                            </div>

                            <div className="bg-emerald-500/10 border border-emerald-500/20 rounded-lg p-5">
                                <h4 className="text-xs font-bold uppercase tracking-wider text-emerald-400 mb-3">Human Rewrite</h4>
                                <p className="text-zinc-200 leading-relaxed text-lg font-serif">
                                    {result.rewrite}
                                </p>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
